version: '3.5.0.{build}'
image: Windows
configuration: Release
platform:
  - x64
  - x86
matrix:
  fast_finish: true
max_jobs: 1
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '3.5.0 ($(platform))'
install:
 - appveyor DownloadFile "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe"
build_script:
 - msbuild /verbosity:minimal /property:langversion=latest "SafeExamBrowser.sln"
test: off

for:
-
  matrix:
    only:
      - platform: x64
  before_build:
   - nuget restore
  after_build:
   - copy /y "Setup\bin\%PLATFORM%\%CONFIGURATION%\Setup.msi" "%TEMP%\SEB_Setup.msi"
   - appveyor PushArtifact "Setup\bin\%PLATFORM%\%CONFIGURATION%\Setup.msi" -FileName "SEB_%APPVEYOR_BUILD_VERSION%_%PLATFORM%_Setup.msi" -DeploymentName "%APPVEYOR_BUILD_VERSION% Setup (%PLATFORM%)"

-
  matrix:
    only:
      - platform: x86
  before_build:
   - nuget restore
   - md "Setup\bin\x64\%CONFIGURATION%"
   - move "%TEMP%\SEB_Setup.msi" "Setup\bin\x64\%CONFIGURATION%\Setup.msi"
   - appveyor DownloadFile "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -FileName "C:\Temp\MicrosoftEdgeWebview2Setup.exe"
  after_build:
   - appveyor PushArtifact "Setup\bin\%PLATFORM%\%CONFIGURATION%\Setup.msi" -FileName "SEB_%APPVEYOR_BUILD_VERSION%_%PLATFORM%_Setup.msi" -DeploymentName "%APPVEYOR_BUILD_VERSION% Setup (%PLATFORM%)"
   - appveyor PushArtifact "SetupBundle\bin\%PLATFORM%\%CONFIGURATION%\SetupBundle.exe" -FileName "SEB_%APPVEYOR_BUILD_VERSION%_SetupBundle.exe" -DeploymentName "%APPVEYOR_BUILD_VERSION% Setup Bundle"
